---
- name: Create Calico
  hosts: master
  tasks:
    - name: Create Calico deploy dir
      ansible.builtin.file:
        path: /opt/calico
        state: directory
        mode: "0755"

    - name: Sync manifests
      ansible.builtin.copy:
        src: "{{ playbook_dir | dirname }}/deploy/calico/{{ item }}"
        dest: /opt/calico/{{ item }}
        mode: "0644"
      loop:
        - operator-crds.yaml
        - tigera-operator.yaml
        - custom-resources-iptables.yaml

    - name: Apply Calico CRDs (1/3)
      ansible.builtin.command: kubectl apply --server-side=true -f /opt/calico/operator-crds.yaml
      register: crd_apply
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Show CRD apply result
      ansible.builtin.debug:
        msg: "{{ crd_apply.stdout }}"

    - name: Apply Tigera Operator (2/3)
      ansible.builtin.command: kubectl apply --server-side=true -f /opt/calico/tigera-operator.yaml
      register: operator_apply
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Show Operator apply result
      ansible.builtin.debug:
        msg: "{{ operator_apply.stdout }}"

    - name: Apply Calico Conifg (3/3)
      ansible.builtin.command: kubectl apply --server-side=true -f /opt/calico/custom-resources-iptables.yaml
      register: config_apply
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Show Config apply result
      ansible.builtin.debug:
        msg: "{{ config_apply.stdout }}"
